### ISSUE TITLE
Thermostat Widget contains no humidity

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.vis-2-widgets-jaeger-design#1]
please add possibility to display humidity of the room

**Comment by Feuer-sturm** [comment]
This is how it looks like with jaeger-design version 1.0.2
humidity is visible

![grafik](https://github.com/ioBroker/ioBroker.vis-2-widgets-jaeger-design/assets/25422320/2b740f8d-8f04-4f5b-bf36-f95e81c98f6e)
