### ISSUE TITLE
Löschen-Icon nicht vorhanden wenn Text zu lang

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.vis-2-widgets-jaeger-design#12]
Wenn Beschriftung zu lange ist, dann wird kein "Löschen"-Icon angezeigt
![image](https://github.com/ioBroker/ioBroker.vis-2-widgets-jaeger-design/assets/35403739/b7708f9f-6628-4587-8969-24c70a65a027)

**Comment by Feuer-sturm** [comment]
@obodeldog please check with current version
