### ISSUE TITLE
Order of Info Widget cannot be changed

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.vis-2-widgets-jaeger-design#3]
Trying to change the order of sub-object in the "Die Info" via drag and drop.
Doesn't work.

Always jumps back.

![image](https://user-images.githubusercontent.com/15639172/225339211-c3893e0d-9359-4c44-aa81-3450143013c8.png)

**Comment by Feuer-sturm** [comment]
Issue is fixed with Jaeger-Design 1.0.2
Issue can be closed @GermanBluefox @xmace
