### ISSUE TITLE
Bestätigungs-Popup verschwindet nicht

### ISSUE THREAD

**Issue by accessburn** [ioBroker/ioBroker.vis-2-widgets-jaeger-design#42]
![image](https://github.com/user-attachments/assets/72d04858-edd4-4b8a-b589-79a9c5103854)

Nach dem Klicken auf "ja", "nein" oder "x" wird die richtige Aktion ausgelöst, oder auch nicht, aber das Popup schließt sich nicht danach.

**Comment by obodeldog** [comment]
Sollte in 1.3.7 (ab heute abend) behoben sein
