### ISSUE TITLE
Design-Widgets werden in Vis-2 nicht angezeigt

### ISSUE THREAD

**Issue by Sash7770** [ioBroker/ioBroker.vis-2-widgets-jaeger-design#46]
Hallo, ich habe mir die Design Widgets gekauft. Leider werden diese nicht in der Vis-2 zur Auswahl dargestellt. Sie sind einfach nicht da. 

Ich habe eine Master/ Slave Verbindung im IoBroker. Die Vis läuft auf dem Slave. Es ist aber egal wo ich den Adapter laufen lasse, Master oder Slave. Die Git-Hub Version 1.3.2 habe ich auch versucht. Im Iobroker ist die gekaufte Lizenz ist gültig.

Master
Plattform: Linux
Admin: 7.1.5
Node: v20.18.0
NPM: 10.8.2

Slave
Plattform: Linux
Node: v20.18.0
NPM: 10.8.2

Widget: 1.2.7 und 1.3.2 versucht.

**Comment by morskipas** [comment]
Hallo zusammen,

ich habe das selbe Problem. Dies tritt bei mir allerdings erst nach dem Update des vis-2 Adapters auf die Version 2.10.8 auf.
Nach diesem Update crashed der Jaeger Adapter leider und wird unter vis-2 auch nicht mehr angezeigt.

Erst nach dem Downgrade des vis-2 Adapters auf die Version  2.9.64 (Backup) läuft wieder alles. Das Problem tritt mit dem Jaeger Adapter in der Version 1.3.1 und auch in der Version 1.3.2 auf.

@Sash7770 : Versuch mal vis-2 in der Version 2.9.64 dann sollte es gehen. Evtl. gehen auch andere Versionen zwischen dieser und der aktuellen Version 2.9.64

Beste Grüße
Frank

**Comment by Pompon61** [comment]
bei mir funktionniert ab Version 1.3.2 nicht. vis-2 in der Version 2.9.64

**Comment by Sash7770** [comment]
Hallo,

ich habe jetzt etwas weiter probiert. Bei mir funktioniert es mit den Versionen 

Vis-2 2.9.64
Jaeger 1.2.5 

jetzt.

**Comment by Risiko98** [comment]
Hallo,
ich habe leider auch das Problem, dass das Jaeger Design nicht mehr funktioniert, allerdings nur in der Cloud von IObroker.
Lokal funktioniert Jaeger in der Version 1.2.7 und Vis-2 in der Version 2.9.64. 
Ich bin mir nicht sicher, wo das Problem liegt, weil ich zwei Dinge geändert habe und seitdem ist das Problem.
Zum einen habe ich das Docker Image aktualisiert und zum zweiten Vis-2 auf Version 2.10.8.
Ein erneutes Einspielen der Vis-2 / 2.9.64 brachte allerdings für die Cloud-Version keine Änderung, und das Jaeger Design funktioniert lokal, aber nicht in der Cloud.

**Comment by Risiko98** [comment]
Bei mir geht es jetzt auch wieder, habe die Jaeger Version 1.3.3 und Vis-2 Version 2.9.64.
