### ISSUE TITLE
Button "pressed" delay for actions

### ISSUE THREAD

**Issue by xmace** [ioBroker/ioBroker.vis-2-widgets-jaeger-design#8]
Buttons always "pressed" for actions.

Idea: only show pressed for 3 seconds after "hitting" it :)

![image](https://user-images.githubusercontent.com/15639172/225369251-714c5c38-ef29-4c4f-9d78-d7fa11f2bf6a.png)

**Comment by Feuer-sturm** [comment]
@xmace please check if issue is fixed with current version
